image: marcopeg/gitpod-workspace-postgres:2.5.0

ports:
  - port: 8008
    onOpen: open-preview
  - port: 5432
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 4200
    onOpen: open-preview